=== Kasluk24/jsqladmin/schema/syntax.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="syntax">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="keywords" maxOccurs="1">
    			<xs:complexType>
        			<xs:sequence>
            			<xs:element name="keyword" type="xs:string" maxOccurs="unbounded"/>
        			</xs:sequence>
    			</xs:complexType>
			</xs:element>
			<xs:element name="quotes" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="quote" type="xs:string" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="sl-comment" type="xs:string" maxOccurs="1"/>
			<xs:element name="ml-s-comment" type="xs:string" maxOccurs="1"/>
			<xs:element name="ml-e-comment" type="xs:string" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== Kasluk24/jsqladmin/syntax/sqlite3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<syntax xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/syntax.xsd">
	<keywords>
		<keyword>SELECT</keyword>
		<keyword>FROM</keyword>
		<keyword>WHERE</keyword>
	</keywords>
	<quotes>
		<quote>'</quote>
		<quote>"</quote>
	</quotes>
	<sl-comment>--</sl-comment>
	<ml-s-comment>/*</ml-s-comment>
	<ml-e-comment>*/</ml-e-comment>
</syntax>
